// Mocks generated by Mockito 5.4.0 from annotations
// in travelbox/test/demo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i13;

import 'package:mockito/mockito.dart' as _i1;
import 'package:travelbox/features/cover_quote/viewmodel/cover_quote_viewmodel.dart'
as _i9;
import 'package:travelbox/features/questions/model/quote_model.dart' as _i5;
import 'package:travelbox/features/questions/usecase/get_quote_usecase.dart'
as _i2;
import 'package:travelbox/features/questions/views/attending_customer/viewmodel/attending_customer_viewmodel.dart'
as _i10;
import 'package:travelbox/features/questions/views/basic_info/viewmodel/basic_info_viewmodel.dart'
as _i12;
import 'package:travelbox/features/questions/views/cover_details/model/card_data.dart'
as _i3;
import 'package:travelbox/features/questions/views/cover_details/widgets/cover_details_card_fields.dart'
as _i7;
import 'package:travelbox/features/questions/views/family_group_cover_details/viewmodel/family_cover_detail_viewmodel.dart'
as _i4;
import 'package:travelbox/features/questions/views/start_end_picker_screen/viewmodel/start_end_picker_viewmodel.dart'
as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetQuoteUsecase_0 extends _i1.SmartFake
    implements _i2.GetQuoteUsecase {
  _FakeGetQuoteUsecase_0(
      Object parent,
      Invocation parentInvocation,
      ) : super(
    parent,
    parentInvocation,
  );
}

class _FakeCardData_1 extends _i1.SmartFake implements _i3.CardData {
  _FakeCardData_1(
      Object parent,
      Invocation parentInvocation,
      ) : super(
    parent,
    parentInvocation,
  );
}

/// A class which mocks [FamilyGroupCoverDetailViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFamilyGroupCoverDetailViewModel extends _i1.Mock
    implements _i4.FamilyGroupCoverDetailViewModel {
  MockFamilyGroupCoverDetailViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetQuoteUsecase get getQuoteUseCase => (super.noSuchMethod(
    Invocation.getter(#getQuoteUseCase),
    returnValue: _FakeGetQuoteUsecase_0(
      this,
      Invocation.getter(#getQuoteUseCase),
    ),
  ) as _i2.GetQuoteUsecase);
  @override
  List<_i3.CardData> get attendee => (super.noSuchMethod(
    Invocation.getter(#attendee),
    returnValue: <_i3.CardData>[],
  ) as List<_i3.CardData>);
  @override
  set attendee(List<_i3.CardData>? _attendee) => super.noSuchMethod(
    Invocation.setter(
      #attendee,
      _attendee,
    ),
    returnValueForMissingStub: null,
  );
  @override
  String get email => (super.noSuchMethod(
    Invocation.getter(#email),
    returnValue: '',
  ) as String);
  @override
  set email(String? _email) => super.noSuchMethod(
    Invocation.setter(
      #email,
      _email,
    ),
    returnValueForMissingStub: null,
  );
  @override
  String get lastName => (super.noSuchMethod(
    Invocation.getter(#lastName),
    returnValue: '',
  ) as String);
  @override
  set lastName(String? _lastName) => super.noSuchMethod(
    Invocation.setter(
      #lastName,
      _lastName,
    ),
    returnValueForMissingStub: null,
  );
  @override
  DateTime get dateOfBirth => (super.noSuchMethod(
    Invocation.getter(#dateOfBirth),
    returnValue: DateTime.now(),
  ) as DateTime);
  @override
  set dateOfBirth(DateTime? _dateOfBirth) => super.noSuchMethod(
    Invocation.setter(
      #dateOfBirth,
      _dateOfBirth,
    ),
    returnValueForMissingStub: null,
  );
  @override
  String get firstName => (super.noSuchMethod(
    Invocation.getter(#firstName),
    returnValue: '',
  ) as String);
  @override
  set firstName(String? _firstName) => super.noSuchMethod(
    Invocation.setter(
      #firstName,
      _firstName,
    ),
    returnValueForMissingStub: null,
  );
  @override
  List<_i5.Quote> get quote => (super.noSuchMethod(
    Invocation.getter(#quote),
    returnValue: <_i5.Quote>[],
  ) as List<_i5.Quote>);
  @override
  set quote(List<_i5.Quote>? _quote) => super.noSuchMethod(
    Invocation.setter(
      #quote,
      _quote,
    ),
    returnValueForMissingStub: null,
  );
  @override
  int get listIndex => (super.noSuchMethod(
    Invocation.getter(#listIndex),
    returnValue: 0,
  ) as int);
  @override
  set listIndex(int? _listIndex) => super.noSuchMethod(
    Invocation.setter(
      #listIndex,
      _listIndex,
    ),
    returnValueForMissingStub: null,
  );
  @override
  int get selectedIndex => (super.noSuchMethod(
    Invocation.getter(#selectedIndex),
    returnValue: 0,
  ) as int);
  @override
  set selectedIndex(int? _selectedIndex) => super.noSuchMethod(
    Invocation.setter(
      #selectedIndex,
      _selectedIndex,
    ),
    returnValueForMissingStub: null,
  );
  @override
  bool get agreeToTerm => (super.noSuchMethod(
    Invocation.getter(#agreeToTerm),
    returnValue: false,
  ) as bool);
  @override
  set agreeToTerm(bool? _agreeToTerm) => super.noSuchMethod(
    Invocation.setter(
      #agreeToTerm,
      _agreeToTerm,
    ),
    returnValueForMissingStub: null,
  );
  @override
  _i3.CardData get cardData => (super.noSuchMethod(
    Invocation.getter(#cardData),
    returnValue: _FakeCardData_1(
      this,
      Invocation.getter(#cardData),
    ),
  ) as _i3.CardData);
  @override
  List<_i7.CoverDetailCardFields> get cardList => (super.noSuchMethod(
    Invocation.getter(#cardList),
    returnValue: <_i7.CoverDetailCardFields>[],
  ) as List<_i7.CoverDetailCardFields>);
  @override
  bool get hasListeners => (super.noSuchMethod(
    Invocation.getter(#hasListeners),
    returnValue: false,
  ) as bool);
  @override
  void setEmail(String? email) => super.noSuchMethod(
    Invocation.method(
      #setEmail,
      [email],
    ),
    returnValueForMissingStub: null,
  );
  @override
  void setLastName(String? lastName) => super.noSuchMethod(
    Invocation.method(
      #setLastName,
      [lastName],
    ),
    returnValueForMissingStub: null,
  );
  @override
  void setDateOfBirth(DateTime? dateOfBirth) => super.noSuchMethod(
    Invocation.method(
      #setDateOfBirth,
      [dateOfBirth],
    ),
    returnValueForMissingStub: null,
  );
  @override
  void clear() => super.noSuchMethod(
    Invocation.method(
      #clear,
      [],
    ),
    returnValueForMissingStub: null,
  );
  @override
  void setFirstName(String? firstName) => super.noSuchMethod(
    Invocation.method(
      #setFirstName,
      [firstName],
    ),
    returnValueForMissingStub: null,
  );
  @override
  void addAttendee(_i3.CardData? cardData) => super.noSuchMethod(
    Invocation.method(
      #addAttendee,
      [cardData],
    ),
    returnValueForMissingStub: null,
  );
  @override
  void setSelectIndex(int? index) => super.noSuchMethod(
    Invocation.method(
      #setSelectIndex,
      [index],
    ),
    returnValueForMissingStub: null,
  );
  @override
  void addCard(_i7.CoverDetailCardFields? card) => super.noSuchMethod(
    Invocation.method(
      #addCard,
      [card],
    ),
    returnValueForMissingStub: null,
  );
  @override
  void toggleAgreeToTerm() => super.noSuchMethod(
    Invocation.method(
      #toggleAgreeToTerm,
      [],
    ),
    returnValueForMissingStub: null,
  );
  @override
  void removeCard(int? index) => super.noSuchMethod(
    Invocation.method(
      #removeCard,
      [index],
    ),
    returnValueForMissingStub: null,
  );
  @override
  _i8.Future<List<_i5.Quote>> getQuote(
      _i9.CoverQuoteViewModel? coverQuoteViewModel,
      _i10.AttendingCustomerViewModel? attendingCustomerViewModel,
      _i11.StartEndPickerViewModel? startEndPickerViewModel,
      _i12.BasicInfoViewModel? basicInfoViewModel,
      ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuote,
          [
            coverQuoteViewModel,
            attendingCustomerViewModel,
            startEndPickerViewModel,
            basicInfoViewModel,
          ],
        ),
        returnValue: _i8.Future<List<_i5.Quote>>.value(<_i5.Quote>[]),
      ) as _i8.Future<List<_i5.Quote>>);
  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(
      #addListener,
      [listener],
    ),
    returnValueForMissingStub: null,
  );
  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(
      #removeListener,
      [listener],
    ),
    returnValueForMissingStub: null,
  );
  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(
      #dispose,
      [],
    ),
    returnValueForMissingStub: null,
  );
  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(
      #notifyListeners,
      [],
    ),
    returnValueForMissingStub: null,
  );
}
