// Mocks generated by Mockito 5.4.4 from annotations
// in travelbox/test/demo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i12;

import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:travelbox/features/cover_quote/viewmodel/cover_quote_viewmodel.dart'
as _i7;
import 'package:travelbox/features/questions/model/quote_model.dart' as _i5;
import 'package:travelbox/features/questions/usecase/get_quote_usecase.dart'
as _i2;
import 'package:travelbox/features/questions/views/attending_customer/viewmodel/attending_customer_viewmodel.dart'
as _i8;
import 'package:travelbox/features/questions/views/basic_info/viewmodel/basic_info_viewmodel.dart'
as _i10;
import 'package:travelbox/features/questions/views/both_cover_detail/viewmodel/both_cover_detail_viewmodel.dart'
as _i11;
import 'package:travelbox/features/questions/views/second_traveler_detail/viewmodel/second_travel_cover_detail_viewmodel.dart'
as _i4;
import 'package:travelbox/features/questions/views/start_end_picker_screen/viewmodel/start_end_picker_viewmodel.dart'
as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetQuoteUsecase_0 extends _i1.SmartFake
    implements _i2.GetQuoteUsecase {
  _FakeGetQuoteUsecase_0(
      Object parent,
      Invocation parentInvocation,
      ) : super(
    parent,
    parentInvocation,
  );
}

class _FakeTextEditingController_1 extends _i1.SmartFake
    implements _i3.TextEditingController {
  _FakeTextEditingController_1(
      Object parent,
      Invocation parentInvocation,
      ) : super(
    parent,
    parentInvocation,
  );
}

class _FakeFocusNode_2 extends _i1.SmartFake implements _i3.FocusNode {
  _FakeFocusNode_2(
      Object parent,
      Invocation parentInvocation,
      ) : super(
    parent,
    parentInvocation,
  );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [SecondTravelCoverDetailsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecondTravelCoverDetailsViewModel extends _i1.Mock
    implements _i4.SecondTravelCoverDetailsViewModel {
  MockSecondTravelCoverDetailsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetQuoteUsecase get getQuoteUseCase => (super.noSuchMethod(
    Invocation.getter(#getQuoteUseCase),
    returnValue: _FakeGetQuoteUsecase_0(
      this,
      Invocation.getter(#getQuoteUseCase),
    ),
  ) as _i2.GetQuoteUsecase);

  @override
  bool get agreeToTerms => (super.noSuchMethod(
    Invocation.getter(#agreeToTerms),
    returnValue: false,
  ) as bool);

  @override
  set agreeToTerms(bool? _agreeToTerms) => super.noSuchMethod(
    Invocation.setter(
      #agreeToTerms,
      _agreeToTerms,
    ),
    returnValueForMissingStub: null,
  );

  @override
  List<_i5.Quote> get quote => (super.noSuchMethod(
    Invocation.getter(#quote),
    returnValue: <_i5.Quote>[],
  ) as List<_i5.Quote>);

  @override
  set quote(List<_i5.Quote>? _quote) => super.noSuchMethod(
    Invocation.setter(
      #quote,
      _quote,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i3.TextEditingController get firstNameController => (super.noSuchMethod(
    Invocation.getter(#firstNameController),
    returnValue: _FakeTextEditingController_1(
      this,
      Invocation.getter(#firstNameController),
    ),
  ) as _i3.TextEditingController);

  @override
  _i3.TextEditingController get lastNameController => (super.noSuchMethod(
    Invocation.getter(#lastNameController),
    returnValue: _FakeTextEditingController_1(
      this,
      Invocation.getter(#lastNameController),
    ),
  ) as _i3.TextEditingController);

  @override
  _i3.TextEditingController get emailController => (super.noSuchMethod(
    Invocation.getter(#emailController),
    returnValue: _FakeTextEditingController_1(
      this,
      Invocation.getter(#emailController),
    ),
  ) as _i3.TextEditingController);

  @override
  _i3.TextEditingController get idCardController => (super.noSuchMethod(
    Invocation.getter(#idCardController),
    returnValue: _FakeTextEditingController_1(
      this,
      Invocation.getter(#idCardController),
    ),
  ) as _i3.TextEditingController);

  @override
  _i3.TextEditingController get idCardCodeController => (super.noSuchMethod(
    Invocation.getter(#idCardCodeController),
    returnValue: _FakeTextEditingController_1(
      this,
      Invocation.getter(#idCardCodeController),
    ),
  ) as _i3.TextEditingController);

  @override
  _i3.FocusNode get firstNameFocusNode => (super.noSuchMethod(
    Invocation.getter(#firstNameFocusNode),
    returnValue: _FakeFocusNode_2(
      this,
      Invocation.getter(#firstNameFocusNode),
    ),
  ) as _i3.FocusNode);

  @override
  _i3.FocusNode get lastNameFocusNode => (super.noSuchMethod(
    Invocation.getter(#lastNameFocusNode),
    returnValue: _FakeFocusNode_2(
      this,
      Invocation.getter(#lastNameFocusNode),
    ),
  ) as _i3.FocusNode);

  @override
  _i3.FocusNode get emailFocusNode => (super.noSuchMethod(
    Invocation.getter(#emailFocusNode),
    returnValue: _FakeFocusNode_2(
      this,
      Invocation.getter(#emailFocusNode),
    ),
  ) as _i3.FocusNode);

  @override
  _i3.FocusNode get idCardFocusNode => (super.noSuchMethod(
    Invocation.getter(#idCardFocusNode),
    returnValue: _FakeFocusNode_2(
      this,
      Invocation.getter(#idCardFocusNode),
    ),
  ) as _i3.FocusNode);

  @override
  _i3.FocusNode get idCardCodeFocusNode => (super.noSuchMethod(
    Invocation.getter(#idCardCodeFocusNode),
    returnValue: _FakeFocusNode_2(
      this,
      Invocation.getter(#idCardCodeFocusNode),
    ),
  ) as _i3.FocusNode);

  @override
  bool get isFirstNameValid => (super.noSuchMethod(
    Invocation.getter(#isFirstNameValid),
    returnValue: false,
  ) as bool);

  @override
  set isFirstNameValid(bool? _isFirstNameValid) => super.noSuchMethod(
    Invocation.setter(
      #isFirstNameValid,
      _isFirstNameValid,
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool get isLastNameValid => (super.noSuchMethod(
    Invocation.getter(#isLastNameValid),
    returnValue: false,
  ) as bool);

  @override
  set isLastNameValid(bool? _isLastNameValid) => super.noSuchMethod(
    Invocation.setter(
      #isLastNameValid,
      _isLastNameValid,
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool get isEmailValid => (super.noSuchMethod(
    Invocation.getter(#isEmailValid),
    returnValue: false,
  ) as bool);

  @override
  set isEmailValid(bool? _isEmailValid) => super.noSuchMethod(
    Invocation.setter(
      #isEmailValid,
      _isEmailValid,
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool get isFormValid => (super.noSuchMethod(
    Invocation.getter(#isFormValid),
    returnValue: false,
  ) as bool);

  @override
  set isFormValid(bool? _isFormValid) => super.noSuchMethod(
    Invocation.setter(
      #isFormValid,
      _isFormValid,
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool get isIDCardCodeValid => (super.noSuchMethod(
    Invocation.getter(#isIDCardCodeValid),
    returnValue: false,
  ) as bool);

  @override
  set isIDCardCodeValid(bool? _isIDCardCodeValid) => super.noSuchMethod(
    Invocation.setter(
      #isIDCardCodeValid,
      _isIDCardCodeValid,
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool get isIDCardValid => (super.noSuchMethod(
    Invocation.getter(#isIDCardValid),
    returnValue: false,
  ) as bool);

  @override
  set isIDCardValid(bool? _isIDCardValid) => super.noSuchMethod(
    Invocation.setter(
      #isIDCardValid,
      _isIDCardValid,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set dateOfBirth(String? dateOfBirth) => super.noSuchMethod(
    Invocation.setter(
      #dateOfBirth,
      dateOfBirth,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set emailController(_i3.TextEditingController? emailController) =>
      super.noSuchMethod(
        Invocation.setter(
          #emailController,
          emailController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set firstNameController(_i3.TextEditingController? firstNameController) =>
      super.noSuchMethod(
        Invocation.setter(
          #firstNameController,
          firstNameController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastNameController(_i3.TextEditingController? lastNameController) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastNameController,
          lastNameController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set idCardController(_i3.TextEditingController? idCardController) =>
      super.noSuchMethod(
        Invocation.setter(
          #idCardController,
          idCardController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set idCardCodeController(_i3.TextEditingController? idCardController) =>
      super.noSuchMethod(
        Invocation.setter(
          #idCardCodeController,
          idCardController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
    Invocation.getter(#hasListeners),
    returnValue: false,
  ) as bool);

  @override
  void toggleAgreeToTerms() => super.noSuchMethod(
    Invocation.method(
      #toggleAgreeToTerms,
      [],
    ),
    returnValueForMissingStub: null,
  );

  @override
  void validateIDCard(String? value) => super.noSuchMethod(
    Invocation.method(
      #validateIDCard,
      [value],
    ),
    returnValueForMissingStub: null,
  );

  @override
  void validateIDCardCode(String? value) => super.noSuchMethod(
    Invocation.method(
      #validateIDCardCode,
      [value],
    ),
    returnValueForMissingStub: null,
  );

  @override
  void validateFirstName(String? value) => super.noSuchMethod(
    Invocation.method(
      #validateFirstName,
      [value],
    ),
    returnValueForMissingStub: null,
  );

  @override
  void validateLastName(String? value) => super.noSuchMethod(
    Invocation.method(
      #validateLastName,
      [value],
    ),
    returnValueForMissingStub: null,
  );

  @override
  void validateEmail(String? value) => super.noSuchMethod(
    Invocation.method(
      #validateEmail,
      [value],
    ),
    returnValueForMissingStub: null,
  );

  @override
  void validateForm() => super.noSuchMethod(
    Invocation.method(
      #validateForm,
      [],
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<List<_i5.Quote>> getQuote(
      _i7.CoverQuoteViewModel? coverQuoteViewModel,
      _i8.AttendingCustomerViewModel? attendingCustomerViewModel,
      _i9.StartEndPickerViewModel? startEndPickerViewModel,
      _i10.BasicInfoViewModel? basicInfoViewModel,
      ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuote,
          [
            coverQuoteViewModel,
            attendingCustomerViewModel,
            startEndPickerViewModel,
            basicInfoViewModel,
          ],
        ),
        returnValue: _i6.Future<List<_i5.Quote>>.value(<_i5.Quote>[]),
      ) as _i6.Future<List<_i5.Quote>>);

  @override
  _i6.Future<List<_i5.Quote>> getQuoteForTwo(
      _i7.CoverQuoteViewModel? coverQuoteViewModel,
      _i8.AttendingCustomerViewModel? attendingCustomerViewModel,
      _i9.StartEndPickerViewModel? startEndPickerViewModel,
      _i10.BasicInfoViewModel? basicInfoViewModel,
      _i11.BothCoverDetailViewModel? bothCoverDetailViewModel,
      ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuoteForTwo,
          [
            coverQuoteViewModel,
            attendingCustomerViewModel,
            startEndPickerViewModel,
            basicInfoViewModel,
            bothCoverDetailViewModel,
          ],
        ),
        returnValue: _i6.Future<List<_i5.Quote>>.value(<_i5.Quote>[]),
      ) as _i6.Future<List<_i5.Quote>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(
      #dispose,
      [],
    ),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(
      #addListener,
      [listener],
    ),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(
      #removeListener,
      [listener],
    ),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(
      #notifyListeners,
      [],
    ),
    returnValueForMissingStub: null,
  );
}
