name: Deploy to withlyla.com
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter test
      - run: flutter build web
      - run: flutter analyze
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync build/web s3://develop-fe-lyla-travel-insurance --delete
          aws cloudfront create-invalidation --distribution-id E3DYERMDOBJ59E  --paths "/*"
          